post http://localhost:4000/
Content-Type: application/json

{
    "task_name" : "get_low_quality_product_image",
    "image_filename" : "special.webp"
}

###

get http://localhost:4000/collections/users
Content-Type: application/json

###

get http://localhost:4000/test
Content-Type: application/json 

### 
get https://play-lh.googleusercontent.com/6UgEjh8Xuts4nwdWzTnWH8QtLuHqRMUB7dp24JYVE2xcYzq4HA8hFfcAbU-R-PC_9uA1