http://localhost:4000/?task_name=get_users
###
http://localhost:4000?task_name=drop_database

### 
http://localhost:4000

###
http://localhost:4000/?task_name=get_products

### 
http://localhost:4000/?task_name=get_shopping_card_items&username=hamedpro

###
http://localhost:4000?task_name=add_a_new_order&name=kk&username=hamedpro